quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.8.6

jooqVersion=3.20.0
jsoupVersion=1.22.1
telegramBotApiVersion=9.6.0
testcontainersVersion=1.21.0
okhttpVersion=4.12.0
assertjVersion=3.26.3
mockitoVersion=5.14.0
pitestVersion=1.15.0
pitestJunit5PluginVersion=1.2.1

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
